[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
wasiat_online = "6rs8fcHe8R5xFM56LyaEHGnxjt5QQcrVZWsMbDphQpe4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/hutomo/.config/solana/devnet/1.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "node migrations/deploy.js"
